# MongoDB Configuration File Template
# This file follows the YAML format.
# Ref: https://www.mongodb.com/docs/manual/reference/configuration-options/

systemLog:
  destination: file
  logAppend: true
  # Define the path to the log file inside the container
  path: /data/db/mongod.log

storage:
  # Define the path where the database engine will store data
  dbPath: /data/db
  # Note: journal.enabled was removed in MongoDB 6.1+, it is now always true.

net:
  port: 27017
  bindIp: 0.0.0.0
